### ISSUE TITLE
Not really publicly available???

### ISSUE THREAD

**Issue by ZitongYu** [vimal-isi-edu/PADISI_USC_Dataset#1]
It seems we signed the agreements and submitted in last December.

There is no response until now?

Thx.

**Comment by mehussein** [comment]
The dataset is still publicly available for non-commercial use. We had an issue with our request tracking arrangement, which affected all requests received prior to Feb 2nd, 2022. After discovering the issue, we contacted all requesters and offered our apology and explanation. If you have not heard from us yet, please, send an email and we will be happy to investigate the issue. We appreciate your patience and understanding!
