### ISSUE TITLE
Cannot connet to padisi.isi.edu

### ISSUE THREAD

**Issue by ZitongYu** [vimal-isi-edu/PADISI_USC_Dataset#2]
Hi,

After we signed the agreement, thanks for the login and download information for  PADISI-Face.

However, even with the username and password, we still cannot connect to the server 'padisi.isi.edu'.
We have tried both FileZilla in windows and shell in Linux, but both failed.

Could you please check whether some problems with the data sharing or downloading?

Best,
Zitong 
University of Oulu

**Comment by mehussein** [comment]
Hi,

I am sorry to hear that. However, this issue is for a specific user request and best handled by email. Could you please send an email with the specific error message(s) so that we can better trace the issue.

Best,

**Comment by ZitongYu** [comment]
Thx, email has been sent.

Best,
