### ISSUE TITLE
Problem about code

### ISSUE THREAD

**Issue by Cassiatora** [vimal-isi-edu/PADISI_USC_Dataset#3]
Hi, Mehussein:
   I read your article "Detection and Continual Learning of Novel Face Presentation Attacks". The paper is very enlightening.
And I want to follow the work. But I found the code link is not available. If possible, can you share it with me? 
    Thank you for your reply.

**Comment by mehussein** [comment]
Hi! Thanks a lot for your interest. Could you please directly contact the first author for the code?
